eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka/
    instance:
      lease-renewal-interval-in-seconds: 5
  instance:
    prefer-ip-address: 'true'   
