# application.yml file of the client service (Spring Cloud Config Client)
spring:
  application:
    name: client-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
